# Generated by Django 4.2.23 on 2025-07-18 05:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('INN', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999)])),
                ('status', models.CharField(choices=[('Active', 'Aктивный'), ('Inactive', 'Неактивный')], default='Active', max_length=120)),
            ],
        ),
    ]
